### DISCUSSION TITLE
Trying to get this working with Tessie integration.

### DISCUSSION THREAD

**Discussion by mhoogenbosch** [flashg1/evSolarCharger#12] [Q&A] [answered]
I'm using an EASEE which has a pretty good integration, but uses service calls to change the A, same like OCPP it needs at least 6A to start. The EASEE doesn't support OCPP. 

For my Tesla Model Y I have the Tessie integration. This is much easier to set up, but comes with a montly fee (too bad). I have tried the entire blueprint, but can't seem to get things working. The A doesn't get adjusted when there is sun.

```
alias: EV solar charger automation - Tesla / Solar / Opladen
description: "31-05-2025: Eerste opzet"
use_blueprint:
  path: flashg1/ev_solar_charger_automation.yaml
  input:
    charger_effective_voltage: sensor.charger_effective_voltage
    charger_max_current: 16
    next_charge_time_trigger: input_datetime.ev_solar_charger_automation
    wait_main_power_net_update: 15
    weather_provider: weather.forecast_home
    tesla_car_name: Martyn
    charger_plugged_in_sensor: binary_sensor.martyn_oplaadkabel
    charger_connect_trigger_list: "[on]"
    charger_connected_state_list: "[on]"
    charger_on_off_switch: switch.martyn_opladen
    charger_charging_sensor: binary_sensor.martyn_opladen
    charger_charging_state_list: "[on]"
    charger_charging_amps: number.martyn_charge_current
    battery_level_sensor: sensor.martyn_battery_level
    battery_charge_limit: number.martyn_charge_limit
    car_location_tracker: device_tracker.martyn_location
    car_at_home_state_list: "[Thuis]"
    car_button_wake_up: button.martyn_wake
    toggle_stop_charger: input_boolean.myev_stop_charging
    select_charge_control_api: k_user_custom_api
```
I have it set to custom API, but also tried Tesla Custom API. 

Is there something obious I could try, or debug? I created the Main Power Net sensor and it shows the correct value. So a Negative when there is sun. The automation doesn't get triggered at all, except for the morning because the sun offset. I'd assume it get's triggered if there is a change in power production, correct?

**Comment by flashg1** [comment, marked as answer]
>  The automation doesn't get triggered at all, except for the morning because the sun offset.

The problem most likely due to incorrect syntax.  You defined a string below, not a list.
```
    charger_connect_trigger_list: "[on]"
    charger_connected_state_list: "[on]"
    charger_charging_state_list: "[on]"
    car_at_home_state_list: "[Thuis]"
```

It should be something like this (examples are in the blueprint entity description).
```
    charger_connect_trigger_list: ['on']
    charger_connected_state_list: ['on']
    charger_charging_state_list: ['on']
    car_at_home_state_list: ['Thuis']
```

> except for the morning because the sun offset.

I doubt it worked after it was triggered due to above incorrect config.  Where did it stop?  You can trace the flow using this [instruction](https://github.com/flashg1/evSolarCharger/wiki/Debugging).  Please send me screenshot of the flow which should give me more info on the issue.

> I'd assume it get's triggered if there is a change in power production, correct?

No.  Please see this for [triggers](https://github.com/flashg1/evSolarCharger/wiki/Design#evsolarcharger-automation-triggers).

**Comment by flashg1** [comment]
Are you using the Home Assistant Tessie integration?  ie. https://www.home-assistant.io/integrations/tessie

The Tessie entity names seem to be same as the one used for Tesla Fleet API !!

Have you tried selecting the Tesla Fleet API in the blueprint?  If not, can you please try selecting Tesla Fleet API to see if it works?

You can try one of these [steps](https://github.com/flashg1/evSolarCharger/wiki/User-guide#automation-cannot-be-triggered) to manually start the blueprint for testing.  No need to wait for the triggers.

**Reply by mhoogenbosch** [reply]
> Are you using the Home Assistant Tessie integration? ie. https://www.home-assistant.io/integrations/tessie
> 
> The Tessie entity names seem to be same as the one used for Tesla Fleet API !!
> 
> Have you tried selecting the Tesla Fleet API in the blueprint? If not, can you please try selecting Tesla Fleet API to see if it works?
> 
> You can try one of these [steps](https://github.com/flashg1/evSolarCharger/wiki/User-guide#automation-cannot-be-triggered) to manually start the blueprint for testing. No need to wait for the triggers.

I'm going to try this later this day, thanks! Change it to the Tesla Fleet API and added the ' around on. Hopefully it'll work.

The only think Tessie doesn't have is a Force Update Data button. I'll try without first.

**Comment by mhoogenbosch** [comment]
Settings are as such:

```
use_blueprint:
  path: flashg1/ev_solar_charger_automation.yaml
  input:
    charger_effective_voltage: sensor.charger_effective_voltage
    charger_max_current: 16
    next_charge_time_trigger: input_datetime.ev_solar_charger_automation
    wait_main_power_net_update: 15
    weather_provider: weather.forecast_asterstraat
    tesla_car_name: Martyn
    charger_plugged_in_sensor: binary_sensor.martyn_oplaadkabel
    charger_connect_trigger_list: "['on']"
    charger_connected_state_list: "['on']"
    charger_on_off_switch: switch.martyn_opladen
    charger_charging_sensor: sensor.martyn_laden
    charger_charging_state_list: "['charging']"
    charger_charging_amps: number.martyn_charge_current
    battery_level_sensor: sensor.martyn_battery_level
    battery_charge_limit: number.martyn_charge_limit
    car_location_tracker: device_tracker.martyn_location
    car_at_home_state_list: "['home']"
    car_button_wake_up: button.martyn_wake
    toggle_stop_charger: input_boolean.myev_stop_charging
    select_charge_control_api: k_tesla_fleet_api
    sensor_main_power_net: sensor.main_power_net
    charge_limit_thursday: input_number.charge_limit_solar_charger_automation_donderdag
    charge_limit_friday: input_number.charge_limit_solar_charger_automation
    charge_limit_monday: input_number.charge_limit_solar_charger_automation
    charge_limit_tuesday: input_number.charge_limit_solar_charger_automation
    charge_limit_wednesday: input_number.charge_limit_solar_charger_automation
    charge_limit_saturday: input_number.charge_limit_solar_charger_automation
    charge_limit_sunday: input_number.charge_limit_solar_charger_automation
    toggle_secondary_power_source: input_boolean.myev_secondary_power_source
    power_offset_from_zero: input_number.myev_power_offset
```

In the tracing it stops at:

stop: Aborting automation because car is not at home or charger not connected.

I checked the home state, I had 'thuis', but that should be 'home' according to debug tools. Same goes for the charging sensor which wasn't correct, but now it should be.

It still stops at the same step. It is currently charging at 16A, so I'm pretty sure it is connected.

Any thoughts on what I could check?

---

Edit

There is a weird thing I'm seeing

I've got this sensor, in Dutch: charger_plugged_in_sensor: binary_sensor.martyn_oplaadkabel

When looking at the tracing, it shows:

<img width="484" alt="image" src="https://github.com/user-attachments/assets/118be808-65ed-4527-ab24-147d5cdf00d8" />

It shows in English. This doesn't exist.

---

Edit 2

Yes, that was an issue. I changed the entity name in HA to martyn_charge_cable and it got to the next step. Let's see what happens next ;-)

The debug info:
```
debug_startingStates: |-
  nowTime = 2025-06-02 21:19:39.306451+02:00
  e_stopCharger = off
  e_useSecondaryPowerSource = off
  e_sunElevation = 2.88
  e_evHomeState = home
  e_chargerConnectState = on
  e_chargerSwitch = unknown
  e_chargerChargeState = unknown
  e_batteryLevel = 19
  e_chargeLimit = 80
```

I'll fiddle a bit more tomorrow, maybe the unknowns get known if I change the entities to English phrases.
