### ISSUE TITLE
OCPP Testing / Feedback

### ISSUE THREAD

**Issue by BJReplay** [flashg1/evSolarCharger#1]
Hi, thanks for your brilliant blueprint.

I note that here https://github.com/flashg1/evSolarCharger/blob/main/ev_solar_charger_automation.yaml#L598 you use the SoC sensor from the OCPP charger.

This sensor is often provided by chargers (as they probably use a standard library for OCPP), but is usually unknown unless the charger is a DC (e.g. CCS) charger.  The OCPP standard includes this measurand and most chargers blindly implement it, but then can't provide it, as they can't access the vehicles SoC when AC charging.

As your use case is typically home charging, most will be AC.  

That said, the sigen DC charger is possibly the exception to the rule that home chargers don't support SoC as it is 25kW DC: https://sigenergy.com/en/products/dc-charger

**Comment by flashg1** [comment]
Thanks for the info.

I need to think about this.  One feature of this automation is dependent on knowing the car's soc.

**Comment by BJReplay** [comment]
> I need to think about this. One feature of this automation is dependent on knowing the car's soc.

I'm doing a similar thing with my automation - I'm using the car's SoC from the integration that supplies it.

Perhaps in your blueprint you can ask for the sensor that supplies the SOC, as you ask for other parameters (or if it needs to be a specific name, ask the user to create a template sensor with a given name), but without this, I'm not sure if it will work.

**Comment by flashg1** [comment]
Hi @BJReplay

A lot has changed with my Blueprint since we last chat!  I am more confident that this is going to work now after updating evSolarCharger with proper OCPP charging status return codes.  Just wondering if you have time to give this a whirl to see if it works?  Any help you can provide is very much appreciated.

For the installation, all helpers are now optional.  Instructions on how to install this Blueprint is here,

https://github.com/flashg1/evSolarCharger?tab=readme-ov-file#installation

Config the Blueprint specifying the power feedback loop sensor (-ve=exported power, +ve=imported power), charger voltage, maximum current, select the charge control API "OCPP charger API" and set you charger name.  That is it!  No need to enter individual OCPP entities.

The EV SOC is optional.  If you have the EV integration for the SOC, you can also enter the Blueprint field "EV battery level sensor".

Looking forward to your feedback on this.  Thanks.

**Comment by BJReplay** [comment]
> Just wondering if you have time to give this a whirl to see if it works?

No, I haven't, mainly because of HA stability reasons. Sunday might be the day to try: Charging will be required (heading out on Saturday for 150km round trip).

**Comment by BJReplay** [comment]
> select the charge control API "OCPP charger API" and set your charger name. That is it! No need to enter individual OCPP entities.

Setting it up now.

What's not clear from the blueprint instructions (but you said I didn't need to do this above) is whether or not you need to set up each sensor, or just one:

Instead of `OCPP: sensor.charger_status_connector` perhaps `OCPP: sensor.charger_status_connector (automatically defined from OCPP charger name)`

Also, see below screenshot for more suggestions.

![Image](https://github.com/user-attachments/assets/77e467ce-73d4-477b-8aa0-30b7b989ff34)

You've got the correct charge current approach, which is great to see.

``` yaml
                - action: ocpp.set_charge_rate     
                  data:
                    custom_profile: |
                      {
                        "transactionId": {{ states(e_ocppChargerTransactionId) | int }},
                        "chargingProfileId": 1,
                        "stackLevel": 0,
                        "chargingProfilePurpose": "TxProfile",
                        "chargingProfileKind": "Relative",
                        "chargingSchedule": {
                          "chargingRateUnit": "A",
                          "chargingSchedulePeriod": [
                            {"startPeriod": 0, "limit": {{ initial_charge_current }}}  
                          ]
                        }
                      }
                    conn_id: 1
```

However, stackLevel is 0 which means that if the user has a default schedule set up in the charger, this won't apply - it needs to be a higher level.  I have a default profile (6A from 9am to 11am, 32A from 11am to 2pm (free charging window), and 6a from 2pm to 6pm) set up so that if my automations don't fire, the default profile takes over.

You can determine the max stack level with this example automation:

``` yaml
alias: Get Charger Configuration
description: Call OCPP Get Charge Point Configuration
triggers: []
conditions: []
actions:
  - variables:
      max_stack_level: 2
  - action: ocpp.get_configuration
    data:
      devid: sn10052312237994
      ocpp_key: ChargeProfileMaxStackLevel
    response_variable: max_stack_level
mode: single
```

You could then use the `max_stack_level` variable to customise the message above to ensure it takes precedence.

I don't have a Tesla style location tracker, but I am running HA on the car (it is a Polestar with android automotive operating system as the car's OS, and HA can be installed).

That allows for things like:

``` yaml
conditions:
  - condition: zone
    entity_id: person.my_polestar
    zone: zone.home
```

Not sure how you'd fit that into your existing model, and, TBH, it's probably low priority for OCPP or custom, because it's not like your telling the car to charge - so you really only need to know if a car is connected to OCPP.

**Comment by BJReplay** [comment]
Another thing: 

![Image](https://github.com/user-attachments/assets/d47aabb8-91e4-4dbf-8bfe-518ce4bba0f4) 

Doesn't accept input_numbers, only numbers.

I figured I'd put in the charge limit from 

![Image](https://github.com/user-attachments/assets/152a67ba-e13a-40c8-838c-54bd4768834e)

But I haven't fully read the code to determine if this is necessary.

I see from https://www.home-assistant.io/docs/blueprint/selectors/#entity-selector that the domain filter accepts a list, so perhaps:

``` yaml
    car_number_charge_limit:
      name: EV charge limit (optional)
      description: >
        Entity to control car battery charge limit in percentage (100% = fully charged).
        EV specific integration must be installed to use this entity.
          * OCPP:         ***Not defined***
          * Tesla Custom: number.charge_limit
          * Tesla Fleet:  number.charge_limit
          * Tesla BLE:    number.tesla_ble_vin_charging_limit
          * User custom:  ***Not defined***
      default: number.not_defined
      selector:
        entity:
          domain: 
            - number
            - input_number
```

**Comment by flashg1** [comment]
Thank you for your quick feedback!  I need to dash right now, but will definitely take a look when I am back this evening.

**Comment by flashg1** [comment]
Thank @BJReplay for your review and in-depth knowledge of OCPP!

I have made the change for ChargeProfileMaxStackLevel.  Basically using that level to override all other charge profiles.  Hope that is ok?

I have released a new beta with the above changes, ie.

v3.0beta23  14/3/2025
-   Get OCPP ChargeProfileMaxStackLevel to override default and lower level charge profiles to set charge current. Thanks @BJReplay.

Please give this a try when you have time.  Hopefully it works and coexist with your existing default charge profile.


> What's not clear from the blueprint instructions (but you said I didn't need to do this above) is whether or not you need to set up each sensor, or just one: I know it says at the top you don't have to, unless not defined, but a reminder could be handy :)

Let me think about this, it is hard to strike a balance between too much information and too little information.


> Not sure how you'd fit that into your existing model, and, TBH, it's probably low priority for OCPP or custom, because it's not like your telling the car to charge - so you really only need to know if a car is connected to OCPP.

I don't think car location is important to OCPP chargers (not to this script anyway), since we are controlling the charger and not the car.  If your OCPP charger is connected to an EV, then the EV is at charger location!  Unlike Tesla, if your Tesla is connected to a charger, your Tesla could be connected to a charger anywhere!


> EV charger limit:  Doesn't accept input_numbers, only numbers.

Not sure if one can mix number and input_number types for writing, but good point.  Let me check.


> I figured I'd put in the charge limit from

Leave them separate.  There is no API to set the charge limit for the Polestar?  If so, then just put the input_number helper in the published charge limit field as a work-around, and set the max charge limit you are comfortable with in the Polestar.


>          domain: 
            - number
            - input_number

Done similar for sensors and binary sensors.

**Comment by BJReplay** [comment]
I won't be able to test until tomorrow earliest, but changes as described look good.

No API reverse-engineered yet for setting SOC limit - it's there, because they have an app that can set it, but not yet available outside of the app.

**Comment by flashg1** [comment]
Also added following to each field description to remind the user, ie.

Entity is automatically defined for the selected API unless it is marked as Not defined.

Please try with the latest version, ie.

v3.0beta24  15/3/2025
-   Removed default tracker for Tesla BLE MQTT API since BLE charge controller is at location.
-   Updated doc.

Thanks

**Comment by BJReplay** [comment]
> Also added following to each field description to remind the user, ie.
> 
> Entity is automatically defined for the selected API unless it is marked as Not defined.

Looks great.

Unfortunately, no sun today (Melbourne), so no chance to try.

**Comment by flashg1** [comment]
Warm and hot in Sydney!

**Comment by BJReplay** [comment]
Tried today, couldn't get it to start charging.  Not sure if it is my OCPP charger, or your template.

Have reverted to my automation for the moment.

**Comment by flashg1** [comment]
No worries.  Thanks for testing.

When you get the chance next time, take a screenshot of where it got stuck, ie. Settings > Automations & scenes > select the automation and then "Trace".  It might give me some clue as to what might be the issue.

The automation can be triggered by sunrise or by you plugging in the charger.  Once it is triggered, it won't trigger again until next time.  For testing, it might be easier just to do a manual run of the automation, ie. Settings > Automations & scenes > select the automation > click on 3 dots on the top right corner > Run actions

**Comment by BJReplay** [comment]
> it might be easier just to do a manual run of the automation

Yeah, I tried that - here's the trace:

Here's where it got stuck - the repeat while:


Executed: 18 March 2025 at 2:03:25 pm
repeat
Executed: 18 March 2025 at 2:03:25 pm
Result:
result: false
repeat/while/0
Executed: 18 March 2025 at 2:03:25 pm
Result:
result: false
repeat/while/0/conditions/0
[Continue if stop button is toggled off]
Executed: 18 March 2025 at 2:03:25 pm
Result:
result: true
entities:
  - boolean.user_custom
repeat/while/0/conditions/1
[Continue if charger is plugged in or charging]
Executed: 18 March 2025 at 2:03:25 pm
Result:
result: false
entities:
  - sensor.sn10052312237994_status_connector

**Comment by flashg1** [comment]
Hi @BJReplay 

Thank you for the pointers and hints.  I think I know what the problem is looking at the charger status in your screen capture.  I didn't implement "SuspendedEV" and "SuspendedEVSE" states because I wasn't sure if they were used.

So all 5 are "plugged in" states, ie.

  # Preparing (EV plugged in but charging yet to start)
  # Charging (EV plugged in with active charging session)
  # SuspendedEV (EV plugged in but not accepting charge)
  # SuspendedEVSE (EV plugged in but EVSE does not allow charging)
  # Finishing (EV plugged in but charging session ending)

I am using the "Preparing" state as the only trigger state to trigger the automation, ie. when the charger is first plugged in.

On starting the automation, states Preparing, SuspendedEV, and SuspendedEVSE will now turn on the charger, and change to Charging state.

As long as the state is "Charging", the automation will continue to run.

When changing from Charging state to SuspendedEV, SuspendedEVSE or Finishing state will turn off the charger and exit automation.

Hope the above is logical and in accordance with your understanding.  Sorry my knowledge of OCPP protocol is limited, but will continue my research on the subject.

Please try with the latest release when convenient.  Thank you for your help.

**Comment by BJReplay** [comment]
> Just wondering how or the circumstances that can trigger the Suspended or SuspendedEVSE states while the EV is charging?

So, SuspendedEVSE occurs (for example) when the sun goes behind a cloud, and the available excess power < 6A x nominal voltage (230V / 415V) and the charger (e.g. through your or another automation) drops the current to 5A or 0A. For an OCPP charger where 6A is the minimum, 5A is telling the charger to suspend charging, without ending the session.

Increasing to 6A is resuming the suspended session.

SuspendedEV is one of the usual transition states after preparing, while the EV does its own ready to charge steps, as well as occurring whenever the EV decides that it is not ready to receive charge temporarily (or permanently - i.e. has reached charge limit set in EV, battery is full, or some other issue.

It could exit that state if (for example) the user increased the charge limit.

In the case of Polestars, there is a bug where a previously deleted vehicle charge schedule is recreated, and the end of this schedule will result in SuspendedEV. This bug affects me - if I notice that the car has stopped charging, I have to delete the schedule, and at that point the car accepts charge again. Admittedly a bit of an edge case, but one I have (unfortunately) seen too often.

**Comment by BJReplay** [comment]
Another note (having reviewed the code change) - from the point of view of someone who is struggling through this from an OCPP only point of view just trying to get his automations reliable (I will share when they are reliable and stable - they are neither, yet): another way of thinking about OCPP states is that you - as the central station - can start or pause or resume or terminate a charging session from any plugged in state. SuspendedEV might mean that the vehicle won't resume charging until it is ready - but in the scenario where it reaches a full (or to limit) charge, but then drops below that limit (e.g. pet mode in a Tesla) it can return to a state of being able to accept charge.

That's a very long way of saying that any mode where the cable is connected can transition to charging. Finishing would require a new RemoteStartTransaction to return to charging, but that could occur by the use clicking on the Charge Control switch in HA

![Screenshot_20250319_091842_Home Assistant.jpg](https://github.com/user-attachments/assets/dfe1bf8e-f7a5-4022-8007-a4511d5ac5d0)

**Comment by flashg1** [comment]
Hi @BJReplay 

Thank you for your insightful comments and experience.  In that case please hold off on the testing.  I need to properly handle Suspended or SuspendedEVSE states!

**Comment by BJReplay** [comment]
> In that case please hold off on the testing.

No worries - I don't charge all that often (if I'm not driving much) so opportunities to charge / test might be limited, but I will try when I can.

Here are my snippets - but I'm not convinced they work all the time - I think I have had issues as well :)

Bear in mind that my automation is a one shot automation that keeps on firing:

Triggers - change in available power

``` yaml
alias: Smart Charge
description: Smart Charge
triggers:
  - entity_id:
      - sensor.throttled_site_power_reversed
    trigger: state
```

General condition at head of automation
``` yaml
condition: or
conditions:
  - condition: state
    entity_id: switch.sn10052312237994_charge_control
    state: "on"
  - condition: state
    entity_id: sensor.sn10052312237994_status_connector
    state: Charging
alias: If Charging Enabled or Charging
```

Relevant variables for subsequent choices:

``` yaml
actions:
  - variables:
      charge_control_on: "{{ states('switch.sn10052312237994_charge_control') == 'on' }}"
      connector_status_charging: "{{ states('sensor.sn10052312237994_status_connector') == 'Charging' }}"
```

dampened_spare_amps is arrived at via an overly complex method (that I'm not sure is right), but attempts to work out spare (or insufficient) amps without swinging the charge amps too quickly because of lag between:

- Offering a charge current and the car accepting it
- The sun going behind a cloud for a moment, but by the time I've turned down the charger, it comes out again.

I can then re-use those for subsequent choices (e.g. increase current, decrease current):

Increase Current

``` yaml
      - conditions:
          - condition: template
            value_template: "{{ charge_control_on or connector_status_charging }}"
          - condition: template
            value_template: "{{ dampened_spare_amps > 0 }}"
          - condition: template
            value_template: "{{ current_charging_amps < max_charging_amps }}"
```

and decrease current

``` yaml
      - conditions:
          - condition: template
            value_template: "{{ charge_control_on or connector_status_charging }}"
          - condition: template
            value_template: "{{ dampened_spare_amps < 0 }}"
```

and suspend for the moment (insufficient power for 6A minimum).  Suspended by setting amps to 0.  Can restart from there if have 6A spare.

``` yaml
      - conditions:
          - condition: template
            value_template: "{{ charge_control_on or connector_status_charging }}"
          - condition: template
            value_template: "{{ new_charge_amps < min_charging_amps }}"
```
