### ISSUE TITLE
Automation does not work with Tesla Fleet API

### ISSUE THREAD

**Issue by andrut1291** [flashg1/evSolarCharger#3]
Hi,

I tried to charge my tesla from solar excess, but unfortunately it does not work for me :(

I use official Tesla Fleet integration (newest version with Fleet API configured). The automation sets the initial 6 amps, turns the charging on, but then enters "alias: Exit script if charger is turned off".

I used your latest version of the blueprint. YAML configuration below:

```
alias: EV solar charger automation
description: ""
use_blueprint:
  path: flashg1/ev_solar_charger_automation.yaml
  input:
    charger_min_current: input_number.myev_charger_minimum_current
    charger_max_current: 13
    car_charge_limit_monday: 100
    car_charge_limit_tuesday: 100
    car_charge_limit_wednesday: 100
    car_charge_limit_thursday: 100
    car_charge_limit_friday: 100
    car_charge_limit_saturday: 100
    car_charge_limit_sunday: 100
    power_offset_from_zero: input_number.myev_power_offset
    toggle_secondary_power_source: input_boolean.myev_secondary_power_source
    toggle_stop_charger: input_boolean.myev_stop_charging
    toggle_set_daily_car_charge_limit: input_boolean.myev_set_daily_car_charge_limit
    car_sensor_charger_pluggedin: binary_sensor.charge_cable
    car_sensor_charging: sensor.charging
    car_number_charging_amps: number.charge_current
    car_sensor_battery: sensor.battery_level
    car_location_tracker: device_tracker.location
    car_button_wake_up: button.wake
    car_button_forceupdate_ha: button.wake
    car_switch_charger: switch.charge
    use_ocpp_api: false
    car_charge_limit_on_bad_weather: 100
```

[trace automation.ev_solar_charger_automation 2025-03-05T11_12_58.074056+00_00.json](https://github.com/user-attachments/files/19088194/trace.automation.ev_solar_charger_automation.2025-03-05T11_12_58.074056%2B00_00.json)
